spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      # Crucial: This unique group ID enables the Fan-Out pattern!
      group-id: notification-group
      auto-offset-reset: earliest

server:
  port: 8085