spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      acks: all
    consumer:
      # Change from StringDeserializer to KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        # CRUCIAL: Tells Kafka to map the incoming bytes specifically to our generated OrderEvent class
        specific.avro.reader: true
      group-id: payment-group
      auto-offset-reset: earliest


server:
  port: 8083