package com.vyshaliprabananthlal.ecommerce.order.saga;

/**
 * 3/1/26 - 21:05
 *
 * @author Vyshali Prabananth Lal
 */

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.vyshaliprabananthlal.ecommerce.order.repository.OrderRepository;
import com.vyshaliprabananthlal.ecommerce.schema.OrderEvent; // This is the class generated by the Avro plugin!
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;

@Service
public class OrderSagaOrchestrator {

    private final OrderRepository orderRepository;
    private final KafkaTemplate<String, OrderEvent> kafkaAvroTemplate; // For sending strict Avro commands
    private final KafkaTemplate<String, String> kafkaStringTemplate;   // For sending standard JSON commands
    private final ObjectMapper objectMapper;

    public OrderSagaOrchestrator(OrderRepository orderRepository, KafkaTemplate<String, OrderEvent> kafkaAvroTemplate, KafkaTemplate<String, String> kafkaStringTemplate, ObjectMapper objectMapper) {
        this.orderRepository = orderRepository;
        this.kafkaAvroTemplate = kafkaAvroTemplate;
        this.kafkaStringTemplate = kafkaStringTemplate;
        this.objectMapper = objectMapper;
    }

    /**
     * STEP 1: Start the Saga (Now using strictly-typed Avro)
     */
    @Transactional
    public void startSaga(String orderId, String productId, BigDecimal amount) {
        // 1. Save local state
        orderRepository.createOrder(orderId, productId, amount, "PENDING");

        // 2. Build the Avro Object. If a field is missing, this won't even compile!
        OrderEvent command = OrderEvent.newBuilder().setOrderId(orderId).setAmount(amount.doubleValue()).setStatus("PENDING").build();

        // 3. Send Command safely within the DB transaction using Exactly-Once Semantics
        kafkaAvroTemplate.executeInTransaction(kafkaOps -> {
            kafkaOps.send("payment-commands", orderId, command);
            return true;
        });

        System.out.println("🚀 Saga Started: Sent strongly-typed Avro command for Order " + orderId);
    }

    /**
     * STEP 4: Listen for the Payment Service's reply (JSON)
     */
    @KafkaListener(topics = "payment-events", groupId = "order-saga-group")
    @Transactional
    public void handlePaymentReply(String payload) {
        try {
            ObjectNode event = (ObjectNode) objectMapper.readTree(payload);
            String orderId = event.get("orderId").asText();
            String status = event.get("status").asText();

            if ("PAYMENT_SUCCESS".equals(status)) {
                orderRepository.updateStatus(orderId, "PAYMENT_APPROVED");

                ObjectNode inventoryCommand = objectMapper.createObjectNode();
                inventoryCommand.put("orderId", orderId);
                inventoryCommand.put("productId", "some-product-id");

                kafkaStringTemplate.executeInTransaction(kafkaOps -> {
                    kafkaOps.send("inventory-commands", orderId, inventoryCommand.toString());
                    return true;
                });
                System.out.println("📦 Payment successful! Sent DeductInventory command for Order " + orderId);

            } else if ("PAYMENT_FAILED".equals(status)) {
                orderRepository.updateStatus(orderId, "CANCELLED_PAYMENT_FAILED");
                System.err.println("❌ Saga Aborted: Order " + orderId + " cancelled due to payment failure.");
            }
        } catch (Exception e) {
            System.err.println("Failed to parse payment event: " + payload);
        }
    }

    /**
     * STEP 7: Listen for the Inventory Service's reply (JSON)
     */
    @KafkaListener(topics = "inventory-events", groupId = "order-saga-group")
    @Transactional
    public void handleInventoryReply(String payload) {
        try {
            ObjectNode event = (ObjectNode) objectMapper.readTree(payload);
            String orderId = event.get("orderId").asText();
            String status = event.get("status").asText();

            if ("INVENTORY_DEDUCTED".equals(status)) {
                orderRepository.updateStatus(orderId, "COMPLETED");
                System.out.println("✅ SAGA COMPLETE! Order " + orderId + " is fully processed.");

            } else if ("OUT_OF_STOCK".equals(status)) {
                orderRepository.updateStatus(orderId, "CANCELLED_OUT_OF_STOCK");

                ObjectNode refundCommand = objectMapper.createObjectNode();
                refundCommand.put("orderId", orderId);

                kafkaStringTemplate.executeInTransaction(kafkaOps -> {
                    kafkaOps.send("refund-commands", orderId, refundCommand.toString());
                    return true;
                });
                System.err.println("⏪ Saga Rollback: Out of stock! Sent Refund command for Order " + orderId);
            }
        } catch (Exception e) {
            System.err.println("Failed to parse inventory event: " + payload);
        }
    }
}